# Generated by Django 4.0.4 on 2022-05-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20200927_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asginatura', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=50)),
                ('etiquetas', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
