# Generated by Django 4.0.4 on 2022-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_projects_delete_projects2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='asginatura',
        ),
        migrations.AddField(
            model_name='projects',
            name='asignatura',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='contenido',
            field=models.BinaryField(null=True),
        ),
    ]
