# Generated by Django 4.0.4 on 2022-05-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_remove_projects_asginatura_projects_asignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='canvas',
            field=models.TextField(default=''),
        ),
    ]
