# Generated by Django 4.0.4 on 2022-06-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_projects_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='contenido2',
            field=models.TextField(null=True),
        ),
    ]
