# Generated by Django 4.0.4 on 2022-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_projects_contenido2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
