# Generated by Django 4.0.4 on 2022-06-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_alter_projects_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='contenido2',
        ),
    ]
