# Generated by Django 4.0.4 on 2022-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_remove_projects_contenido2'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
