# Generated by Django 4.0.4 on 2022-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_projects_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='version',
            field=models.TextField(default=1, max_length=3),
        ),
    ]
