# Generated by Django 4.0.4 on 2022-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0015_projects_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='creado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
